### ISSUE TITLE
Alias !quack command to work with !honk also

### ISSUE THREAD

**Issue by talk2MeGooseman** [talk2MeGooseman/twitch-interactive-overlay#66]

**Comment by HTMLGhozt** [comment]
The _easiest_ way to alias `!honk` to `audio/quack.wav` would just be to add another object in [`AUDIO_COMMANDS`](https://github.com/talk2MeGooseman/twitch-interactive-overlay/blob/master/app/scripts/helpers/audioFactory.js#L1). Is there a more elegant way to achieve this functionality?

**Comment by talk2MeGooseman** [comment]
@HTMLGhozt I agree with the easy right with this but was also thinking of a more elegant way to solve this. One thing that might be easy to do its for `command` to also support an array of strings, if its an array, check to see if the triggered command is contained in that array. Thoughts?

**Comment by HTMLGhozt** [comment]
The open PR implements aliasing via arrays, but I wonder if it would be more elegant to have CSV (comma-separated values) instead. You wouldn't have to check if commands were an array.
```js
audio.command.split(',').forEach(fn)
```
seems to me more elegant than:

```js
Array.isArray(audio.command)
  ? audio.command.forEach(fn)
  : fn(audio.command)
```
