### ISSUE TITLE
New Audio Command: !doh

### ISSUE THREAD

**Issue by talk2MeGooseman** [talk2MeGooseman/twitch-interactive-overlay#69]
Add in a new audio command `!doh`

I would like to add in a command that play Homer Simpson stereotypical D'oh explicative to the overlay. Find a good a good audio source for this command and add it in.

Good source for audio that might help on the hunt: https://www.myinstants.com/index/us/

Instructions:

1. Add audio source to: app/static/assets/audio
2. Add new command information to /app/scripts/helpers/audioFactory.js
3. Test audio to make sure it isn't too loud compared to other audio commands, tweak the volume if it is

**Comment by reneecampanilla** [comment]
Will take this

**Comment by reneecampanilla** [comment]
Here's my PR: https://github.com/talk2MeGooseman/twitch-interactive-overlay/pull/74

**Comment by reneecampanilla** [comment]
Current update: fixed merge conflict 😄

**Comment by talk2MeGooseman** [comment]
There was another individual that created a PR before yours, but If you like, would you be interested in adding a command for `!haha`. The audio would be Nelson from the Simpsons saying "haa haa"
